baseURL: https://www.todaypgh.com/
languageCode: en-us
title: "TodayPGH - Inspirational Stories of Pittsburgh Educators"
params:
    description: "TodayPGH tells the stories of educators around Pittsburgh. To inspire. To lift up the profession. To provide support and inspire the next generation of educators."
    images:
        - img/social-feature.jpg
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
googleAnalytics: UA-17188743-28
