name: forestry
on:
  pull_request:
    branches: [forestry]
#    types: [closed]
jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
#      - name: Update forestry branch
#        run: git push origin HEAD:forestry --force
