name: github pages
on:
    schedule:
        - cron: '0 22 * * *'
    push:
        branches: [master]
jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: '0.69.2'
                extended: true
            - name: Build
              run: hugo --minify
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
