name: lint
on: [push]
jobs:
    js:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Read .nvmrc
              run: echo ::set-output name=NVMRC::$(cat .nvmrc)
              id: nvm
            - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
              uses: actions/setup-node@v1
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
            - name: Install dependencies
              run: npm ci
            - name: Lint JavaScript
              run: npm test
    sass:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Read .nvmrc
              run: echo ::set-output name=NVMRC::$(cat .nvmrc)
              id: nvm
            - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
              uses: actions/setup-node@v1
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
            - name: Add problem matcher
              uses: xt0rted/stylelint-problem-matcher@v1
            - name: Install dependencies
              run: npm ci
            - name: Lint Sass
              run: npm run lint-sass
    md:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Lint story front matter
              uses: namoscato/splinter@v1
              with:
                  src_paths: content/story
